[package]
name = "jpeg_encoder_nif"
version = "0.2.0"
authors = ["Håvard Lindset"]
edition = "2018"
rust-version = "1.60.0"

[lib]
name = "jpeg_encoder_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
jpeg-encoder = "0.5.1"
